spring:
  application:
    name: clean-architecture
  config:
    import: optional:classpath:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: localhost       # endereço do broker RabbitMQ
    port: 5672            # porta padrão do RabbitMQ
    username: guest       # usuário padrão (troque para seu usuário)
    password: guest       # senha padrão (troque para sua senha)
    virtual-host: /       # virtual host padrão, normalmente "/"

logging:
  level:
    org:
      flywaydb: DEBUG

  api:
    version: /v1
    base:
      path: api
