services:
  ride-db:
    image: postgres:15
    container_name: ride-db-postgres
    env_file: .env
    restart: always
    deploy:
      resources:
        limits:
          memory: 2048M
    ports:
      - "${HOST_DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: